---
title: "Miscellaneous"
subtitle: ""
format:
  html:
    include-before-body: ../header.html
    resources: 
      - applets
      - coi-serviceworker.js
---
## Previous Research Topics

- [Grothendieck–Teichmüller group](GT.qmd)

- [$\mathrm{Out}(F_n)$](Out(F_n).qmd)

## Applets

Here is a collection of experimental mathematical and non-mathematical applets I made.

- [Visualize Runge Phenomenon](applets/rungesphenomenon.html)

- [Guass Elimination Solver](applets/guassianelimination.html)

- [Keyboard Piano](https://github.com/wangyenshu/keyboardpiano)
  - [web demo](https://wangyenshu.github.io/keyboardpiano/): This web demo has no sound.

## Some projects that I am associated with: 

### GAP-System Emscripten Port:

```{=html}
<div id="gap-container" style="text-align: center; margin: 20px 0;">
  
  <button id="btn-launch-gap" class="btn btn-primary">
    Start GAP
  </button>

</div>

<script>
  document.getElementById('btn-launch-gap').addEventListener('click', function() {
    const container = document.getElementById('gap-container');
    
    const iframe = document.createElement('iframe');
    iframe.src = "https://wangyenshu.github.io/gap-wasm/index.html"; 
    
    iframe.style.width = "100%";
    iframe.style.height = "500px"; 
    iframe.style.border = "none";
    iframe.style.backgroundColor = "#000"; 
    iframe.style.display = "block";
    
    container.innerHTML = '';
    container.appendChild(iframe);
  });
</script>
<script src="coi-serviceworker.js"></script>

[COPYRIGHT](gap-wasm/COPYRIGHT)
[LICENSE](gap-wasm/LICENSE)
[How to build](https://github.com/wangyenshu/gap-wasm/blob/gh-pages/README.md)

### FriCAS Emscripten Port:

```{=html}
<div id="fricas-container" style="text-align: center; margin: 20px 0;">
  
  <button id="btn-launch-fricas" class="btn btn-primary">
    Start FriCAS
  </button>

</div>

<script>
  document.getElementById('btn-launch-fricas').addEventListener('click', function() {
    const container = document.getElementById('fricas-container');
    
    const iframe = document.createElement('iframe');
    iframe.src = "https://wangyenshu.github.io/fricas-wasm/index.html"; 
    
    iframe.style.width = "100%";
    iframe.style.height = "500px"; 
    iframe.style.border = "none";
    iframe.style.backgroundColor = "#000"; 
    iframe.style.display = "block";
    
    container.innerHTML = '';
    container.appendChild(iframe);
  });
</script>
<script src="coi-serviceworker.js"></script>

[Source and Credit](https://github.com/wangyenshu/fricas-wasm)

### SageMath in Browser:

[https://wangyenshu.github.io/SageMath-in-Browser/](https://wangyenshu.github.io/SageMath-in-Browser/)

[Source and Credit](https://github.com/wangyenshu/SageMath-in-Browser)

### Singular in Browser:

[https://wangyenshu.github.io/Singular-in-Browser/](https://wangyenshu.github.io/Singular-in-Browser/)

[Source and Credit](https://github.com/wangyenshu/Singular-in-Browser)

### Macaulay2 in Browser:

[https://wangyenshu.github.io/Macaulay2-in-Browser/](https://wangyenshu.github.io/Macaulay2-in-Browser/)

[Source and Credit](https://github.com/wangyenshu/Macaulay2-in-Browser)

### CoCoA in Browser:

[https://wangyenshu.github.io/CoCoA-in-Browser/](https://wangyenshu.github.io/CoCoA-in-Browser/)

[Source and Credit](https://github.com/wangyenshu/CoCoA-in-Browser)

### KASH3 in Browser:

[https://wangyenshu.github.io/KASH3-in-Browser/](https://wangyenshu.github.io/KASH3-in-Browser/)

[Source and Credit](https://github.com/wangyenshu/KASH3-in-Browser)

### Regina in Browser:

[https://wangyenshu.github.io/Regina-in-Browser/](https://wangyenshu.github.io/Regina-in-Browser/)

[Souce and Credit](https://github.com/wangyenshu/Regina-in-Browser)

### Magnus in Browser:

[https://wangyenshu.github.io/Magnus-in-Browser/](https://wangyenshu.github.io/Magnus-in-Browser/)

[Source and Credit](https://github.com/wangyenshu/Magnus-in-Browser)

### Prover9 and Mace4 in Browser:

[https://wangyenshu.github.io/p9m4-in-Browser/](https://wangyenshu.github.io/p9m4-in-Browser/)

[Souce and Credit](https://github.com/wangyenshu/p9m4-in-Browser)

## Mathematician Who Went through Extreme Hardships

- Hua Luogeng, [Biography in English](https://archive.org/details/hualookengbiogra0000wang)
- To be Added


::: {style="border-top: 1px solid #ddd; padding-top: 10px; margin-top: 20px; color: gray; font-size: 0.8em;"}
Document last rendered: {{< now >}}
:::
