---
title: Interview Presentation
subtitle: PhD in Mathematics
format: revealjs
footer: "Yanshu Wang - Nankai University"
css: "antibes.css"
simplemenu:
  flat: true
  barhtml:
    header: "<div class='menubar'><ul class='menu'></ul><div>"
  scale: 0.32
revealjs-plugins:
  - simplemenu
  - pointer
chalkboard: true
self-contained: true
incremental: false
scrollable: true
author:
  - name: Yanshu Wang
    email: wangyenshu@outlook.com
    affiliations: Nankai University
date: last-modified
---

## Background {data-name="Background"}

**RELEVANT COURSEWORK:**

- MATH0068 Computers, Set Theory and Logic (Mathematical Logic) 91
- MATH0132 Abstract Algebra I 88 (Honor Class)
- MATH0134 Abstract Algebra II 95 (Honor Class)
- MATH0055 Number Theory 92
- MATH0079 General Topology 84 
- MATH0102 Commutative Algebra 97
- MATH0136 Galois Theory 96 
- MATH0151 Real Analysis 81 (Honor Class)
- MATH0162 Lie Groups and Algebraic Groups 90 
- MATH0051 Functional Analysis 93 
- MATH9100 Topics in Algebra A- (at Temple, Braid Groups) 
- MATH0153 Algebraic methods in Combinatorics (Algebraic Combinactorics)

**AUDITING:**

- Elementary Algebraic Topology
- Analytic Number Theory
- Differential Manifold

## Research Interest {data-name="Research Interest"}

::: {.centered-list}
- Algebra, Number theory and Arithmetic Geometry
:::

## Research Experience {data-name="Research Experience"}

- Mitacs Globalink Research Internship, Mentored by Prof. Maxence Mayrand, Université de Sherbrooke, May 2025 – Aug 2025
- Senior Year Individual Study, Mentored by Prof. Vasily Dolgushev, Temple University, Jan 2025 – Current
- Polymath Jr., Online, Jun 2024 – Sep 2024

## Mitacs GRI {data-name="Mitacs"}

- constructed new GKP code from the Abelian varieties on the cyclotomic field $K = \mathbb{Q}(\zeta_n)$
- write the SageMath script for working with GKP code constructed from the cyclotomic field

## GKP Code From Abelian Varieties {data-name="Mitacs"}


## Senior Year Individual Study {data-name="GT"}

- introduced a more streamlined version of the groupoid $\mathsf{GTSh}$ of $\mathsf{GT}$-shadows
- contributed to the SageMath package for working with $\mathsf{GT}$-shadows

## GT-Shadows {data-name="GT"}


## Polymath Jr. {data-name="Polymath"}

- proved that the Riemann surface of the $K_9$ dessin is a degree $9$ cover of the Bolza surface $y^2=x(x^4-1)$ with covering group $(\mathbb{Z}/3\mathbb{Z})^2$
- computed the equation for the Abel-Jacobi map of the Bolza surface $S_B$
- constructed a degree $9$ cover of the Jacobian $\mathrm{Jac}(S_B)$ 
- obtained the equation for $K_9$ dessin

## Equation for $K_9$ Dessin {data-name="Polymath"}



## Future Plan {data-name="Future Plan"}

**short-term plan**

- try to pass the qualification exam in the first year
- finish the required courses and teaching duties
- find an advisor

**long-term plan**

- become a Mathematics professor at a research institution
- make original contributions to the mathematics community

## Thanks for Listening {.center}
