---
title: "Information for Referees"
navbar: false
format:
  html:
    page-footer: false
    toc: true

format-links: [pdf]
---



This page is for the convenience of referees. 

#### Basic Information:

* **CV**:
    + <a href="https://wangyenshu.github.io/wangyanshu/CV">HTML version of CV</a>
    + <a href='javascript:(function(){var w=window.open("https://wangyenshu.github.io/wangyanshu/CV","popup","width=800,height=600");w.addEventListener("load",function(){w.print()},true)})();'>PDF version of CV</a>
        
* **Transcript**: 
    + <a href="https://wangyenshu.github.io/wangyanshu/referee/nk_transcript.pdf">Transcript at Nankai University</a>.[](nk_transcript.pdf)
    + <a href="https://wangyenshu.github.io/wangyanshu/referee/temple_transcript.pdf">Transcript at Temple University</a>.[](temple_transcript.pdf)

Below are tables that contains

* The graduate schools I am going to apply to
* Deadline to submit the reference letter
* My Statement of Purposes for that school

Below is an iCalendar file (.ics) that can be imported to your Calendar app. This file includes a notification for a reference letter for each of the listed graduate programs, with the event date set 22 days before the application deadline.

 * <a href="https://wangyenshu.github.io/wangyanshu/referee/reference_letter_notifications.ics">Download iCalendar file</a>.[](reference_letter_notifications.ics)

#### Mathematics PhD Program in USA:

| Graduate School Name | Deadline | My Statement of Purposes |
|--------|--------|--------|
| University of Iowa | Jan. 15, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uiowa.html">Statement of Purposes</a> |
| University of Colorado Boulder | December 1, 2025 at 10pm Mountain Time | <a href="https://wangyenshu.github.io/wangyanshu/SOP/colorado.html">Statement of Purposes</a> |
| Colorado State University | TBD | <a href="https://wangyenshu.github.io/wangyanshu/SOP/colostate.html">Statement of Purposes</a> |
| Oklahoma State University | February 1, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/okstate.html">Statement of Purposes</a> |
| University of Arkansas | February 1, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uark.html">Statement of Purposes</a> |
| University of Utah | Jan 1, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/utah.html">Statement of Purposes</a> |
| University of California, Los Angeles | December 13, 2025 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/ucla.html">Statement of Purposes</a> |
| University of Michigan | February 1, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/umich.html">Statement of Purposes</a> |
| University of Arizona | January 1, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/arizona.html">Statement of Purposes</a> |
| Brown University | December 8, 2025 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/brown.html">Statement of Purposes</a> |
| Ohio State University | December 5, 2025 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/osu.html">Statement of Purposes</a> |
| Pennsylvania State University | January 5, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/psu.html">Statement of Purposes</a> |
| Indiana University, Bloomington (Michael Larsen) | January 15 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/indiana.html">Statement of Purposes</a> |
| University of Pittsburgh | January 15 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/pitt.html">Statement of Purposes</a> |
| University of Oregon | January 15 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uoregon.html">Statement of Purposes</a> |
| University of Georgia | January 1 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uga.html">Statement of Purposes</a> |
| University of University of Virginia | January 15 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/virginia.html">Statement of Purposes</a> |
| Michigan State University | December 1 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/msu.html">Statement of Purposes</a> |

-----

| Graduate School Name | Deadline | My Statement of Purposes | Interested Instructor |
|--------|--------|--------|--------|
| Boston University | January 15, 2026 | TBD | |
| University of Minnesota Twin Cities | December 15 | TBD | |
| University of Illinois Urbana-Champaign | December 15 | TBD | |
| University of Wisconsin-Madison | December 15 | TBD | |
| Northwestern University | December 31 | TBD | |
| Brandeis University | January 15 | TBD | |
| Boston College | January 20 | TBD | |

#### Mathematics PhD Program in Canada:

| Graduate School Name | Deadline | My Statement of Purposes |
|--------|--------|--------|
| McGill University | January 15th | <a href="https://wangyenshu.github.io/wangyanshu/SOP/mcgill.html">Statement of Purposes</a> |
| Concordia University | October 3, 2025 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/concordia.html">Statement of Purposes</a> |

#### Mathematics Master Program in Europe:

| Graduate School Name | Deadline | My Statement of Purposes |
|--------|--------|--------|
| University of Bonn | January 15, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uni-bonn.html">Statement of Purposes</a> |
| Berlin Mathematical School | December 1, 2025 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/BMS.html">Statement of Purposes</a> |
| ALGANT | January 31, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/ALGANT.html">Statement of Purposes</a> |
| Universität Duisburg‑Essen | January 15, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uni-due.html">Statement of Purposes</a> |
| University of Münster | January 15, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/uni-muenster.html">Statement of Purposes</a> |
| ENS Lyon M2 | January 23, 2026 | <a href="https://wangyenshu.github.io/wangyanshu/SOP/ens-lyon.html">Statement of Purposes</a> |
| Paris Graduate School for Mathematical Sciences | Feb 3, 2026 | TBD |
| Fondation Mathématique Jacques Hadamard | End of Jan, 2026 | TBD |
| Mathematics and INteractions in Toulouse | Feb 9, 2026 | TBD |
| University Grenoble Alpes M2 | Should start on Feb? | TBD |
| Université de Lille M2 | Should start on Jan, 27? | TBD |
