---
navbar: false
format:
  html:
    page-footer: false
    toc: false
  pdf:
    pdf-engine: weasyprint

format-links: [pdf]
---
<div style="font-size: 2em; font-weight: bold; text-align: center;">MOTIVATION LETTER</div>
<p style="font-size: 1.5em; font-weight: bold; text-align: center;">YANSHU WANG</p>
My primary research interest lies in the area of number theory, and arithmetic geometry. I have completed research in several specific topics but I am open to exploering new ideas in number theory, and arithmetic geometry as well. The relevant advanced courses I finished include (Algebraic) Number Theory ,Commutative Algebra, Galois Theory, Lie Groups and Algebraic Groups.

{{< include _general_sop.qmd >}}

My short-term plan after admission is to try to finish the required courses, attend colloquia, find an advisor, and begin my dissertation work as soon as possible. My long-term plan is to to become a Mathematics professor at a research institution and make original contributions to the mathematics community. I like École normale supérieure de Lyon’s historic architecture and large area of green spaces. I believe that École normale supérieure de Lyon is the best place for me to build a successful mathematical career.
